// Theme State - persisted via HydratedBloc
import 'package:equatable/equatable.dart';
import 'package:flutter/material.dart';

// NOTE: This file uses manually-written JSON serialisation helpers instead
// of @JsonSerializable codegen, so there is no 'part' directive and no
// generated .g.dart file. This avoids a spurious build_runner WARNING on
// every build while keeping the serialisation logic readable and auditable.
class ThemeState extends Equatable {
  const ThemeState({this.themeMode = ThemeMode.system});

  factory ThemeState.fromJson(Map<String, dynamic> json) =>
      _$ThemeStateFromJson(json);

  final ThemeMode themeMode;

  Map<String, dynamic> toJson() => _$ThemeStateToJson(this);

  @override
  List<Object?> get props => [themeMode];
}

// Generated by build_runner. Implementation recreated here so the file
// compiles even before code generation runs.
ThemeState _$ThemeStateFromJson(Map<String, dynamic> json) {
  final mode = json['themeMode'] as String?;
  return ThemeState(
    themeMode: switch (mode) {
      'light' => ThemeMode.light,
      'dark' => ThemeMode.dark,
      _ => ThemeMode.system,
    },
  );
}

Map<String, dynamic> _$ThemeStateToJson(ThemeState instance) =>
    <String, dynamic>{
      'themeMode': instance.themeMode.name,
    };
